default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dima
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: Advertising_development

test:
  <<: *default
  database: Advertising_test


production:
  <<: *default
  database: Advertising_production
  username: Advertising
  password: <%= ENV['ADVERTISING_DATABASE_PASSWORD'] %>
